     ‚*---------------------------------------------------------------*
     ‚* LOG-CPY                                                       *
     ‚*---------------------------------------------------------------*
     ‚*                                                               *
     ‚* AUTOR         :  A. PIEGER                                    *
     ‚*                                                               *
     ‚* ERSTELLT AM   :  14.10.2010                                   *
     ‚*                                                               *
     ‚* FUNKTION      :  VARIABLEN FÜR LOG-CPY                        *
     ‚*                                                               *
     ‚* ÄNDERUNGEN:                                                   *
     ‚* DATUM      VON   GRUND DER ÄNDERUNG                           *
     ‚*                                                               *
     ‚*****************************************************************
     ‚*
       01  LOG-CPY.
            COPY DDS-PCFGSTSF  OF PCFGSTS.
                 06 LOG-DA               PIC 9(1).
     ‚*€
